[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "1310c3dbd87e28f72121604673273b13542a94ee"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "58a9ef007d3d71b4ac2703d15451ec5cde25d80e77de0e52b83c359d7c0e49da"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "c2fb655f510727dc6428a0535e60c4dc5b110b67"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "82b6dcac3ed1d63f4a44979a0d3973f7f14bcdea27e486a1e7f3933e05018493"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d7da0159d2045e6481ca687022fb0ad40264a704"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7738b2e6ef3967684415c754adf67b96d09c6d934086534a38128a0509b56f99"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "14097a101b7d18211964f631e6460846d0073ffd"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "9e5a8976e40b61b607ffd697a128f93a7792ce3e1e4a7ae015291298706cc2fe"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0ad987a90c7bdf3064722cae7f28446ac953698f"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "adf11d67bb6f941b176c8fc4116e42ddeefb4b9fd70ed385bd849bb19064f1c9"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0450f317916ca96dc785ee8881ab78d118daedb6"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "57516e86c2ed729fb19fb49d39bb7a9a6a31cd76d1f1af0e1411a64b0e0d842c"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "11de5330980355935b32a73af44248baf286eb9b"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "d28bb9fb31618b2066280ea29872a50f26de81d5259247284d0caf83af347ba7"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "da28b0f945517a94f0cb28fb0c154b4b3a75a73e"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "28d5786898c593a9bb63b124293d27354582c6255955fb3eea21e372da22272c"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "d1eb3951c768934370c1712efb42e7679a1336e1"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "aa44ddce7c0760655f8358d8096a49277c1d5a01cfde70bdbe370c01ed8c37b1"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "2abf9d89ce900455e83a76a24be5fff784b1c02e"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "69e4a72caf160930e512d8bd5208bb5f4162746109d269b098c36d12ee9afc4e"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "a2c3c1e4bd0671f015385f9beb92617fbe0b2ac9"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "688cf3fd56153b1b75dfd7430f115cfc8e4c86c29bccbe5fc56c5ccc14265f8a"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.3.27+0/UserNSSandbox.v2023.3.27.x86_64-linux-musl.tar.gz"
