[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "4e06431c75c38241c8037e55e11d517c8411fd27"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "fb144198540c31f9f0e277f3b290460896def024079e8716e295e731be4059c2"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "35fdae9630adf41b0792099cc29a05d03f7b46d2"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "3496c004aa4d969d336600fb23f1b2f4db16846de7d2a733dcb2890518737dd7"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ad76f81fe9afcaa772c86de3f8596573d027cc51"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "b0681e2fabac80ca7ec2981c94f0e5bcf2d94c07bf85ae70bcffe83fc97fa5f9"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "42e4a2d484abccdff66a753e94ef4fbd432e39a4"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7e167f39f37a24606ec8cf63a6c237ef98145d1abb219c2a80609c099b8d09c6"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "563f31a55525371a3c1606e12e95dfb964a5371e"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "74dbd689201075160f9ebeccafc08d9719de8d9e6f9a23001d5101af97e9e952"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d13effe81e9d7d60ca21df01fe84dea9475403a"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "960a5fec5250182a8ea1d9bfddf9b700cad37ab8b881a055d6585d5f416fa59b"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "9a086dfa3b624dea020965f3250f8f5f05234ab9"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7dabad7da1e69e7f90dcd6b6dd5ff40b879635ac8a5f5402a11dd34c8d19b80f"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "d49da7b925dabd824316d96e7474710fd1be57da"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "468363880126cc7358a30a5f7040460fadc4cd850a10ec67025f574c06ded39f"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "b45af3753796c6dc2f9910578642b7e8bc66702e"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "843ed45b9c508db272219c07c391a7e71b87e10cb78f25a64d362c7e0af075a0"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "018fc8901f98daddaa3a603bc97d8bfa13819d34"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "b91a99187446c5d76cff76b0a4d7255a144da08bb78e78f7ed5fb9099ecbd218"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "dd47a499ea4f3523c6e0b74067d28300832f9bae"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "f2618916237c00b37e95ef978a2bc8bd1ff6caaa1c641fad5f9ecc5ba06fb7e2"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.10.3+0/UserNSSandbox.v2022.10.3.x86_64-linux-musl.tar.gz"
