[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "de16b811b61a7471cdef586995b95d31ecc7edff"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "5e594cb2a49e80909a380713828df21fb22f99a6e4575aff9926c74615d01139"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "11cbf3aa8c8737693740cd4bd9ad4884b26e33d3"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "5b9ee49d3d6485370a0dcff282cf80a2f88ffe1e74c26cf878a82d1bbbba247e"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "81ba3792eba01d831acde02b5e372486fda5f5b8"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "eac0768172fe8c7938fe8bf63e463ac198cffcb31507cbb136ce79ee68940f52"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7bb6db050b6ad6a029a02722fef90f0ee878b87"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "5a2a35c68b69129e556a24a4ccb2f6234f659fba51ecc252f61d866658785af5"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "64c2341cbc8c49e3827fb24971384736c3fb9f1a"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "20864417c72c4610c1385d948304e1d4ba80faf9540600637f9eac321639b1a4"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3068630e12f101674a09ca3f9341521aa49d000a"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "0dead167b8f6015b00a2a6b450db88971cae40b33c63fdaccb699b6ea0560355"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "82b057339783269eebd6e82ba1a3cfe6bddc3ea8"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "d73074405fac618667473dcbcd75a1464a6bc4276ea2458c266bf1224e1a3c4e"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "fe266419998051442da2792746a7d0ab21ff99f6"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7d55f6d02118fc4b2bd160dbf00c6d9935fd8a6047612bb2bf5b481d91f8d8e1"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "7874d2821bd15e9c226fa1654819cbf6ec90a483"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "c62b8028be25b820b8ce35e561548ade36591aff59a9589b2f3ebb5e358b1af6"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "15bac938273a159eff4b5defabca3810dda5307b"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "727a45184dd596db38e4d8babe5d1ee62f1df1b37f52bd7ee5467a98b202c148"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "d13a716073569e190fa3cab2520766ce8fe3f1d7"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "b19fb25a05d3d7a393c0f9d586c55b325adbf84882eed47f4267988b5622fad4"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.10+0/UserNSSandbox.v2022.3.10.x86_64-linux-musl.tar.gz"
