[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "c0d3aaa4774dff878af714e95779075590efffab"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "fe0e6d03880c67ae42dd581e68a4f30099f2d5ef9bfd3e3354e6dca9c35fa571"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "7b3bea692c4bd7dfa76dafd0feba5d11a15e3388"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "91c9a83b56fd59267b54a587f41470e151ce922551392dde4154c2f7106a3638"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "12900c68299658df6c07f0428b5648653a13034a"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "57d58c567d9f36527d1d56ff6d4090b2204fa7252222b08a8138bc327479bf4c"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7f791eac5b3278c92aded97b9f3a085e74e90c63"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "857d0ae096a70305c32cd66b4bbb7c2cf18652a6f885000795b1bff3786dc522"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03dcb97a0d533cdb48f74f0b5a1b1fc442df77e2"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "17ca535a52c7ed7d33e450495e4668703d0b2853d9005ea732f32244c3fe4f81"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dfd6dac39df3ff2af21b82d2af7b49655e2f171a"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "e083f08b681b537107c127a39a3008c76a92c5da16c3a7bb7a88de74ac27073a"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "d4f639dc7a39a49cfa5a383e5685b9bb376ec0cd"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7c23a9dfa4684e13adb893a23ddfc341fc2c26ad5021b5835479b37344392800"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "7b743c717ac29558c126377a6e67fcf6e67a42b5"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "bc998904e570c88a87c4260b4e347e621fc9044e8cb3b49b2d93ab38663ad98a"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "cd647eeebcb699cd326e466a0f8e423aebf4f710"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "395d56348b062790af7660c32f6911c5510289783749fb7fed08581bd3804cdf"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "90884ac9255ef060697c8aef579c04c984557570"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "9f3380a405c1b10f38f2762202897edaa21023850396e3272605c5784f836cc8"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "8eabbf78677af4adf2c153a7b7431714a068638c"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "e1d8fb589541337153b5d13563b57b19a4a4ec30332797398f644e3d329631b2"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.1.6+0/UserNSSandbox.v2022.1.6.x86_64-linux-musl.tar.gz"
