[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "118e8a4b1553dc0a69ce0e38dbf65768ac7faf40"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "16632a1fa1405737ccfce96ed656bfca92871f9bc4b20b199fd825915c691350"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "7483eb4111566d0d9eb95550313c4f20e153cf3a"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "47583180636ed89cecbe890b4a58533535d40c7161ed20f2dcabaeb352623f6c"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75785a0baaeaf48cf3b0ca0f32cb90825ecdda98"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "2ba902356047d00e29358ab20af4007214c9003722be7125d9cd6f20ca902766"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d54bc718009020eed4c383792766c4ff507dba3f"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "f293be83ff0000c1fd247574c099870f788ef4a72fc98d787b3b472a41da660d"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "53940e83bd920627c2b9377a8178df26ca38ff95"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "96781b004178c9861967b56981ff64c308696999c6f9cb2ce6ada66482ac10d3"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "464ac472bc6498ce690993b82fac99e6cf2d8f74"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "517ce80c740f8aaff3dc1a6332ce66fe6f11d7ed6b548ddbfeb8af678c01c28b"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "ce56355ad94c28d4dbf06af890dac0bba6ef9012"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ff145cc30d4682a501eb677b6c3c8013c6955099f335e0718595e485ccfc03db"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "78967a3fa994bd243e65232ba3f9c55f023edb33"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "83fedf86034b5d954e4cac7365a4400cac291ca91bc068f49db579ad68f90586"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "3b7c1efcc607f5ac44d96dfe7e4a0f85311eb5f2"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "2acec55240c9b31711ec1e440efaaff434195e0a117d5c1c58ebf67db3f4c72b"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "9ee2c2df7f016278f1cdd1e2b644ef8474885d6f"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "d1d414059d1bfe7a0a0c8f4d0031d3ccd1b63d86d73b93b9b73366287c1f5485"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "b057d579faae4b3cf8422e999284323ab9f458c4"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "218d4dbb012779d5b15de06b03cbe4f02b028a4e45db3f612f38bdd038862f06"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.8.1+0/UserNSSandbox.v2022.8.1.x86_64-linux-musl.tar.gz"
