[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "508e4685975e74e2eec42ba4d84379a07abd7b88"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "bb1732fa5c485c89b04f19a5d13f291403ba38327951046b6a62efa781cfa5cd"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.3.4+0/UserNSSandbox.v2021.3.4.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "35455ab66448e90c5cc85b3c8b18c51a7753c4a7"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "0182a60362b8177f78f0bb9b532dfbdeb97ebc553e7eaea980a0ff6f114f3aed"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.3.4+0/UserNSSandbox.v2021.3.4.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cbe392a280b2c4f1c9a077d66c4848d341fc5ecb"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "4a1019ea8ecbd5a4d907392f7973ec6becf453669f2b966778797034a706270b"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.3.4+0/UserNSSandbox.v2021.3.4.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0584207e12e2d3c042ac8ec28e935387674ab611"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "65d375d999b50e66ce284d4fa0f11a2b26026a03d82de388a4d20bc2cc7c857a"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.3.4+0/UserNSSandbox.v2021.3.4.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "2234ba3483271518d79e0fb43aafdee0477d7052"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "95008cc42a94119e2cbfc1372a92b22cb3c49baf60bb589d6584e750ff8f2064"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.3.4+0/UserNSSandbox.v2021.3.4.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "d3b9094a0ee6b55df52c55de6c93e0a96abc154d"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "81cf0dedca36903d93bd082bf5cbb0c894018297cde99af8f9ae37852fa1a759"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.3.4+0/UserNSSandbox.v2021.3.4.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "7a2921b07a5415b1e812f92df2eef340c5f22eab"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7e7405aa65c914e20a56989c7a00a74d374a27a4cdc2b15e9e89b223ebb093a3"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.3.4+0/UserNSSandbox.v2021.3.4.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "6d02f8c3fbbd649ef5745376f04e8fdd2089f77e"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "a12ee5b9ce4c8d97d6061aab057694e9934b25800e2233677d876711be558266"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.3.4+0/UserNSSandbox.v2021.3.4.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "a287aa1bb49ecea83a7ce721910eed71750c2d9a"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "5a020524f6386948babb1dbbcef008d67724f13c13b9d363be81aaab554825cc"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.3.4+0/UserNSSandbox.v2021.3.4.x86_64-linux-musl.tar.gz"
