[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "17f71b663f005b30412ab326934362e67b761036"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7b6c9b4540cc3b9254d30aacfd29ad879f4977c183fc752abdf4817884036e33"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.16+0/UserNSSandbox.v2021.4.16.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "5afd79ca28ad5413a76c110dc083a10872123719"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "378291b69aaef3456539ce1f997d5f216e4da73082d1957a431cd179f651548f"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.16+0/UserNSSandbox.v2021.4.16.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94ac36986b210e4e94927a63ef56eb7bee10501d"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "5912a2fa658e311daa9522d72810f8837fb2948c4c6624d8d18f77deca749d5e"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.16+0/UserNSSandbox.v2021.4.16.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94e86ee50fbc7ea04c2d9b6056134e55e668535d"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "b196f9bb4d5a834fa8f64ac39ce5c4544e3419bf480fc22e523214cfd82700f0"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.16+0/UserNSSandbox.v2021.4.16.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "be9949239a3ee54dee0c95c3f426c3ca4cf238c7"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "47da9ece11e3871c6842d1ad950c6a2d7aae3f001f3edbc408abb4ae7cfc30c8"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.16+0/UserNSSandbox.v2021.4.16.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "995574402a2fefbfb77c78a268b875d937692ab4"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "72e836bbfa5ad8cc62d3077e58321ba8bafe34a633b8e2da2172bec91a84dfbe"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.16+0/UserNSSandbox.v2021.4.16.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "b1f5834cb7df267ec47b00434240843f483b2148"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ca88a4965d6b6bc8d3c8ec5ef3b814629539963d51ce442ce1ea49def734a285"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.16+0/UserNSSandbox.v2021.4.16.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "b75badd28f02d9a4824aa829a7537d1c6f39fb13"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "2bdf3df6649ea167d2efa0c313a60996150d8a74cc7f4076d926caa714083269"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.16+0/UserNSSandbox.v2021.4.16.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "39d20d86f8bdaa5ade14d84b9f6929faa96f0eef"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "924b9d10ce1fcc2acc5cd01e95ffd2528696bc2ef81d67de7699db52c991f515"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.16+0/UserNSSandbox.v2021.4.16.x86_64-linux-musl.tar.gz"
