[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "0cc4f7507c1cc8f51fd697dffd29d3c1c1c34959"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7813d1707085cd9282477b782073eb39f37fb86acdeb43df0b1bdb174f5a938a"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.21+0/UserNSSandbox.v2021.4.21.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "4fe8a4f7646f9bd1b2706707877a6d54ab9b8cba"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "4ab624a8eebd544f078764372d1af6905f3a041c42683daa011233422374ad21"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.21+0/UserNSSandbox.v2021.4.21.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "53c70e0b4d458a7d67fb4eba6b5390c8dfcbe6e1"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "60f9c0b62290ecb96e91eb6ab07265296959aa677c9e786987fec0c0de4e1eb8"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.21+0/UserNSSandbox.v2021.4.21.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a5b944cb85ddfefea41d64b5c419d98ce96c874a"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "1666f9c771d628183c8d1e117d1a43fd772f48fcae402ca6af657aa1fbe0e1c4"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.21+0/UserNSSandbox.v2021.4.21.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "fc4a74f4ea6dfe1668c754988424caff64bb279f"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "3ad246fd34e02097f31c0afb9944e1a22ef95e496071696a844d3570ce4c775c"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.21+0/UserNSSandbox.v2021.4.21.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "4c7fc4a22f93762b9538408336be4c8ef9aed7ee"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "a5dfcc29678893bf19e0c0ee7a4f85800877dd34562425c21d3793c887b0b974"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.21+0/UserNSSandbox.v2021.4.21.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "acf01d860a582b773a9ae893814760c6ad91bc3f"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "6d08add8cc1580ebaf0a91bb3513cc0a94cfe8f0a5b653ad45975a2b9bf54eb1"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.21+0/UserNSSandbox.v2021.4.21.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "24f75c010b370411acca6cad7d380ebc5ca0811e"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "4de15d823a21369180c4dc5b4266ef5d6dd2a3b86032e8a2a28c39a6223689f2"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.21+0/UserNSSandbox.v2021.4.21.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "ba48cb5014a79891f42059d5d738a93b76a019e4"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "268a282aa0d457acefd9fe20cc9acb603a410680bd92bbde0acac284149957a6"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.21+0/UserNSSandbox.v2021.4.21.x86_64-linux-musl.tar.gz"
