[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "5b27e10968a7bf51acb5c79742ee8dd8bf02cbda"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ec1480ccee1afaae1fbcbf272df9e3cb6576f3e06d8290cf954f4e9c8b8c4dc1"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "b472ebc1d0e867870f2c3fb18f886b28c8e74ee9"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "6058753a9c4a485a10cc0ddd973dc6be24035cc6ddd873454bf1ac77c5a0286a"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3309dfafc23de3fa4c020e362fcca29280a0bccf"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "759b31c01bab48fdc7b9c334412b6158363fe6a9e84e04aa57f44d7b12060ed3"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b895639c1b9483e33e10912b87e15afa532e2df5"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "e29efe3c7dcc8a216d1e879fa18b547bff65803645fea83270b5a3ec61106dec"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ed19fa7d9a9c271402e9088e8ee82099ceea116b"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "98d41cbeb2944eb2297fe0d4ba523069e0944fc2f68426c6c1978dc04b3efa73"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8bb5fc46ead44c853db7c87e604d734749f9523f"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "c8c16e25c2ed8239548cadf5aeb9ee793c6f9fd43a99de39bc70d2a5a4af5d35"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "39008f0ed75a52ec18fb44376dc09e7a43d1e7a6"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "3a9da0a2ddfb9d5669780c94df9aaf9a6fc0d54429b9646bfe367df1aed7ccce"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "c56ab3ad8f3c9f075f76cdb145506a324c54f2e9"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7429b6e88b8bed8861067e6575d285a40003ad96887cac82b94b8ecaeddea3ca"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "e6cbd1434e3c340c59fc29e0d0c520c1ea60de18"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "b68ea602d3a43cd92c3ef791fdf0212ad12fb9fcd2af2f97f9f0503916b7c33f"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "riscv64"
git-tree-sha1 = "401561565481fb7bc9f8654d80ae6a3634208e1c"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "46d27545cbf01f2040dbc8ecdc98773b538739ea7816831208c5f3679d92ded4"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.riscv64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "90bf5674f6dfab8f15adf30f6dd9e5456f2e9e88"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "04da6fc1587f232c54bb93183be18b4cc902b83941863971e9713b8be53ba72a"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "2c6606d6ffbfe1506ddf39e74fc761257017ee0e"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "76bf985786e49081417a12a89e78bf7436eba9e71cc2296d8a983bdb6cebac5c"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2025.1.28+0/UserNSSandbox.v2025.1.28.x86_64-linux-musl.tar.gz"
