[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "2d9af41db4a841ec662a063e3f8c06d833624440"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "f79e991ec48823daf0bdbe18aa586ac6202f1d13e0056fd0ae6dfb60438dca90"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "cb36709d3ae2a4c78229c761cb1ed0f4f70ce82d"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "30ecf47548d2f82f3d7c3a93b7f0032eb96d46ec1dd712f7c9763f64ab2d1e75"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "63f3642867ecec141d1231b1f87f96358bd7df9d"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ace6677bdd3d2124d1014acc2f1caaa57e67b54f7c5d17db1740a33543017355"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce68da60c2a2c6b14944c3f867862e2be3859d79"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "0f761e5e8e643e81064a0a00f210e35eba34ec0b010024a84afcba5d845e0a32"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4f6863f2f279ab8db800d002997cf3edda660955"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "de94f6ea5eb79c07f5cbf8773b3c3dab683439254790b227827eef075b6c2595"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8231bdbe56939651916522f7ab9b7b987d5cd310"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "752093856c33efa21b37b3eda843117c010ad6f0535200b374c6c854d3b88214"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "5ead91066e269561a24bccbc302925891cc385a8"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ebdac314b1b2778870ffbb96925281c76f04c6ddfbb65390a70a8c728b4d883d"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "14f8c8a75ff8a52033591a019685bbf1811d1723"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "0ca8eee35bddf4e40e2631a012abdcadb917e8889cff60c1668286b182d261e9"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "65ed2542f672d21b44309677cabf65f55a366f12"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ddab7779ed500a77586618cb7641fd417bc615a4d4bc15ce5d756666ac1cd24c"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "7edcdee739cab1df69a4496fb73708e917e9f08c"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "b7f99299024808a0ce694d8367cdc7e57066168094822f30dbd9905d7f95a8cd"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "f4a8198b12a460393b9c873ab3418efcd2d87c93"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7d0a954f947d6ab69dd93923304c181b23a1d18a8b2e00172fc0b607ef6ff6e1"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+0/UserNSSandbox.v2022.3.30.x86_64-linux-musl.tar.gz"
