[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "99c10eee63ac4b43fd09e875a944e3448343a928"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "e8d2db6407e12710ba2c8fa8a92ad2266963787542e05a73a2796dfc0a24ce68"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.8.18+0/UserNSSandbox.v2021.8.18.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "078b57312f221d48be4dfa7def07aeceba98bfd8"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "8acede6fefea1a2b23fd0ee835b1a79a4a492e3be622917315d4e0de639bede4"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.8.18+0/UserNSSandbox.v2021.8.18.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "771b379881b69e187a715fdd8adf4f339b9844b7"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "0dcf9b3c3b1084ee0096bc028e7356b217a5f360e58d2b7b906ec43325ea2386"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.8.18+0/UserNSSandbox.v2021.8.18.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4ca438dca01c4a7b0416c80359a359098f4beb1"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "840c52a49c72251d993c0f8e23cd4a5ef7b90b7d0455a8fba28a4bb181554fd6"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.8.18+0/UserNSSandbox.v2021.8.18.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "c55f3a624b8845e7759317024640f15566f7190d"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "b9c53e8d0fc839d2769d798b379eb1d60f664ea761e8a4d3eca69368ec06563d"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.8.18+0/UserNSSandbox.v2021.8.18.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "2a6ad87cff1eb42e2b13857e4493f0505d5d9f8b"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "0004768b9340265cb8ac4daee43770674d1f6d36053de7ac79ee5ba1fb72b35c"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.8.18+0/UserNSSandbox.v2021.8.18.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "372f90dac2fbd5b3c8871409c6bff3ba85bb1401"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "4a73decd03f82bfcc274a9859c94d89916c971ed734aeac46b39dbda5a3c1714"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.8.18+0/UserNSSandbox.v2021.8.18.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "5cb3e869933e4793abb03da0e168e1eeef0ec056"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "8d0a8e7f5eb8397741ff315642ecc981e594615e0cad8c3ed9f75c10b9451f5b"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.8.18+0/UserNSSandbox.v2021.8.18.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "bf22c0afed306814d3f7495d29bdd449fb621f43"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "15d8b94d5b58379b6e4118a28ee906e41e4d23f54ba16b58b7c7fa7cf212ffbd"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.8.18+0/UserNSSandbox.v2021.8.18.x86_64-linux-musl.tar.gz"
