[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "5c28278c21004da651c14c7f68a94935f355639e"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "bcf655ce660405d3a5658abf5d1b112c12f9ae7152cda11dc83fa772d17933f0"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.20+0/UserNSSandbox.v2021.4.20.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "5918e0e4fcd7de005073776c04bbb358d1dc2766"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "a27cb5081bc7d20a3fcc6ed2d873ecddb58eaf54f026a545b2f3ea011747df85"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.20+0/UserNSSandbox.v2021.4.20.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f9442c41effef173cc3cdb508f23a371354bf17c"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "92e46664061149ded2408f63ccf9a30cd0f94457065cdd4e975473b5a4daff6e"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.20+0/UserNSSandbox.v2021.4.20.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1505a2a61640fbe55593a09c0103cb502ef1b8c2"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ef4958e42be8b97ab95f61c1aa9faa6b2f003f97cbbb766ae77d43509e2454d7"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.20+0/UserNSSandbox.v2021.4.20.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "3d427f11b6364a5ed032591c3b1ff18ed83116c1"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "1d0866a8c88af140fc0350d7904480cbcee3aa121d06f1bd3c333195ceb6d29e"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.20+0/UserNSSandbox.v2021.4.20.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "a6d47c59dbffe68b14cccf7b36a75f4e7e4d5784"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "0377b1c28c82f2a567735bf9ee0a836fffe58438d5a2e49ce0b55717ee65fa85"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.20+0/UserNSSandbox.v2021.4.20.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "f1a727384c8a422d7b1e942b70b05a8daf25104c"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ad8b9819ab6377c74abf9ebe9c75c805b2e68ea2dcdbefb90f7d6ad6272bcf4e"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.20+0/UserNSSandbox.v2021.4.20.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "c563e82aaea7989891ddc3c961ec6c5c21bb48b7"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "a83cc898a90258fb72ff977790e0ae0a97ff4118009d48e1dfa343d65cf6d511"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.20+0/UserNSSandbox.v2021.4.20.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "df6ae6ccc158986395b92dec2a6925e77fbdd796"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "2495166485c3a9d9d98c11ac790aa402ff473a07fac88645b24859949274e595"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2021.4.20+0/UserNSSandbox.v2021.4.20.x86_64-linux-musl.tar.gz"
