[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "2c6060d458e877dfefdcaf553a906a06746a9c45"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "f529609a870233f9ffaa2240667c5b7817ceb542dc432f55b066a7ab66526b66"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "dc2d8c969b1a525a60755fc002bf55c04a3a209b"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "7d7c0265cf832ec1f77f50aea8909c7b973f3434c04276e32fab04f282ce49c1"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b6a91d7afd57bb72f60cbc8f0d97522bff25e7f"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "14e90dc65e64639536aa5af1d4964eac9b6fba4ffb56fee5dad198d04b86380b"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "508e4c7c8658c26448e427471d8067e8e7260f59"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "a0c681d1222faf8757db79cd711e1b7fcc65dd70df078bfbc7a59c7b94ad875f"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7461dc6c4708d6ca5da2ec5db8c7ccf7cce92bbc"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "17937581af7970fe99e30400d14b6f0e04e69010def532831b69fb834c9221fb"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ebfdaf3cc413ded8b2f90e7e069c4099f6235757"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "6ce70e41b420848f420f7151c22a02969420100c35e553933a30d648b3d70ad9"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "b65e486596aad37fa91f53c51c816e735ae60654"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ef2fe97036d0297d2d83122f8d3428bf7fef79b5ebd6ada6c056b99b5abed57e"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "1daed4cacdada70beebc19c72ed25ac135da56fb"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "c7f7e5bb5f970ca4d000a1d05f1325fa51c873bc135afc4d9bdb63f04e46ad7c"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "2d270316c62859fa7084a5feb1822a6b37fd9ed6"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "fb695d5e872efb9d078077cb8c64e301865da1baa16995121001d01846976237"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "10fc4718a39759ac8e811cf4fa22db2b33bba509"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "26ae7100c430b17a2cf773a889d1ed6e3a399c1277a4c81fda8d5b2226f68231"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "4316fc38f66029b0d0b2a5bcd0de22807dc20b07"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "c17cd8223f8d9c1276e0f272f5e4dc02f66028a317619b09026ce767b16f321b"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2022.3.30+1/UserNSSandbox.v2022.3.30.x86_64-linux-musl.tar.gz"
