[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "206e663f8ce29b8139cbd7af2fcb032c25e7017a"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "d00fe8c13afad5ccb9a17045dea3e0e3eec2b9893af4f84597da3ee0731891e2"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "fc2d1254894a4b219ab567fccdb655f361e8b300"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "db2b455ee0edb221381005e409f4f8380c49d7cc2696cf65bb0360c0d7baaf3d"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e3e52ba4ab09f729c0505d1fa3b37c37b4746e82"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "67e98090261caa8e3fd8c30c6c72bef2fe8bb1ceff3074a7c736216006a3f80f"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d3489b17f57a197063813f0c419482dfd746101"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "5728cd14a8d09d17979d7a4a9bc504182c495d8cca47123334617057b360d041"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "263dcb31878cf25e9838314e76681eb268d5bba5"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "e8a517a968afb8ef4a70f30b95931b930ccbb5d5f2665572e42956451cdb195c"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b71507be3cd8d25a18e0e52dc1ad059dbbeae4d8"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "82649e0b5d46cfc4eb8af375079f02be4f8725a4483aadb2f39d6740b8340500"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "3d61e9f02376f44e4419da984f9b1a5654370b35"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "990e77926f25df620ada4844a62560948eeb4c1cba9111e6859d6fbdbc84e024"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "fc35824c7a44a22b00564d6e0400659c69b13bab"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "f3eb1638b4fbf3168e56cbb7f1efc04d7b76d6394fc1944e6ecad9001f358fcc"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "527345fa48414e674fb8b404141032dd261f4ef8"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "d71927c07c6e6b74e393f49ff45fc1575a97599a033dc806c33b41d10f93add9"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "f112fcb2d776f8a748a4a5da2b088a312882edce"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "85d1b5dd4d4ef1d7bfa7274ac32c9b3c5f9e612ae066504c19918d0f9b3b25c7"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "b057ac24309ef5553d802ec51a9ae9c9d932b703"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "8aa687837efc565677dc3c8ca330f0f1206cff8249475f5ac7ed2217ed61bbb3"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.8.8+0/UserNSSandbox.v2023.8.8.x86_64-linux-musl.tar.gz"
