[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "e0972024e0557f8b93c184d5b58effdffcdb1eec"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "25977e73328270a424fb8d63b883d2162e185ca8bde01ae202a630d4d08a96f4"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "fd027ffd5eb83084a494edd92459b04267a31193"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "74df2d54478944944abc531839881525bab8a9e69673f6bfbe87ad523011074f"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "87d19dcac45285cb7fb847bb7670d82317a3d373"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "52d68af7c80e66f20a4df6cecd49e2df7f1589e9cd95aa1a2117b5aa28225731"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab952d0480aafe0f0bf580655e9e8ce0b4c1355b"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "5602f2eafa35c718e2bd145b267d40aa65f19e030970212f16d7a248aa163bcf"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "235619e28fc293087d49db7043ba90fd60f91a97"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "5e6105426a1a7487245ee76c5f8043e6c746f8df7e452adcea82eab7dc113c81"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "483f29bb870bdbe6286ab5df6d3f90018bb9d5bb"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "40dd7a490f30c5ab549523b9107dd26154aa628fff2ae2b06725eb91781c4e83"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "8fbd000fb324061c2b86bcf6aea8eac9a695ca8c"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "c3bedb33de0f566e17b9d3314ee85b48da7b4a5f51266238890031cc27359a36"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "4f3f66fe656122cf7d56aa4fb6e678c28c594185"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "595978d4313740eb4a0b7c83a1fd94967ba6d4dc85e2babaa82864b2205d68be"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "9e790076191176322acda58684c8e8bf026110b1"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "8fd3f994662297d5796cfbc9845df3aa5fc4ed4187b0fb1926d6b50ad4a7e657"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "38b4ddc29c126213fb62e5a3298fb0062b8a0463"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "47251234a9047ae1b163a2b9d8ba8a091db0a2ee8c74c354d2aaed7637f41fab"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "7b045c976911595e10bfea8726fa17ee432f0af5"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "11cc11df6468988c5407d767daa4ea2db20497de6ae0b1c92462cad28c8f397b"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2023.9.26+0/UserNSSandbox.v2023.9.26.x86_64-linux-musl.tar.gz"
