[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "0dcf1aefdb6920f57757fcae0d031c3d25da1d06"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "8d4852129930f7ca0a2cd3610d9ea3a74e6161c19a4211553992a3f2abb18884"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.aarch64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "aarch64"
git-tree-sha1 = "e101ca498b023792c9f6a939744d1aaa87e9c051"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ed32bbefabce2b92e3d01cfaacf9771c21d16ee1408b1bd4446b5a3e41fa5b71"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.aarch64-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7d2b5573c2cb615895ff1240550c3d89771b214"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "ab1ec0943ff62128fc13f7e507a1a4857a3db387efbb962801e5f9b632c3f885"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.armv6l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "46f7d665a8ed6569921c36ad11ac5ef92107a724"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "8302d1b919b106c3c13e4a7257599a16f60a1bb032df44aeb4fce2401fe3dfb2"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.armv6l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4bca19ae5e2c7fa862a83564964ea719e2fbb09"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "5b04655959664afc68bfbfe7b3c65fed84a09e8f228c6b3c65f6c3767a8768b0"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.armv7l-linux-gnueabihf.tar.gz"
[[UserNSSandbox]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "82db4ea12f87e30e0ec0bddc0b55ad5b04037192"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "9722b02fd705d2b9c1020fa86170deb70dd377aa05941b05bf8fa19ebcf17e17"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.armv7l-linux-musleabihf.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "4927e74eae063b43cb4b7f8b5125b91d4341f876"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "0af6c3c0d737c71c8962df04e504a91e40395350e6f7083c31ec5256c9a606dc"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.i686-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "i686"
git-tree-sha1 = "d5cdc4c7c8a6fd02c1d2f87fdc3402c3f48cb24c"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "51fb07dbb411a5abdfe1f73ac5ef87be561ae09eecc8b16105f4cb0b3369987d"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.i686-linux-musl.tar.gz"
[[UserNSSandbox]]
arch = "powerpc64le"
git-tree-sha1 = "38436238dae36e5433d9894b3a04bd44b4bfeaf2"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "befb28a18bdc935eeec86ceb0ae6acbf2d7eedd7d983178997e8c479f140b325"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.powerpc64le-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "d15e0a743703c1b4b50ef70e717b07473b24b2cd"
libc = "glibc"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "982ed4e57d5a205bea64e9518d138096127c604161ee022d2c7c389fe67ce236"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.x86_64-linux-gnu.tar.gz"
[[UserNSSandbox]]
arch = "x86_64"
git-tree-sha1 = "05103c8d3fed0774f9a54e7e5d384a02bb4be677"
libc = "musl"
os = "linux"

    [[UserNSSandbox.download]]
    sha256 = "e8c46a1af42319228cc0148848496a7d9b0802cf398036c144254c9776055921"
    url = "https://github.com/JuliaBinaryWrappers/UserNSSandbox_jll.jl/releases/download/UserNSSandbox-v2024.6.23+0/UserNSSandbox.v2024.6.23.x86_64-linux-musl.tar.gz"
