# Autogenerated wrapper script for UserNSSandbox_jll for x86_64-linux-musl
export sandbox

JLLWrappers.@generate_wrapper_header("UserNSSandbox")
JLLWrappers.@declare_executable_product(sandbox)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        sandbox,
        "bin/sandbox",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
